project_id = "xibiayicnyvvfbmdcuai"

[functions.auto-daily-guide]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.insurance-advice]
verify_jwt = false

[functions.crop-prices]
verify_jwt = false

[functions.crop-prediction]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.daily-guide]
verify_jwt = false
